spring:

  datasource:
    url: jdbc:mysql://localhost:3306/restexample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
